### ISSUE TITLE
Is there a way to use scalars with correct typings?

### ISSUE THREAD

**Issue by bennyk8y** [remorses/genql#115] opened 2023-03-27 11:59 UTC
Hi, in the schema we have scalar Date which in the backend will transform every input with this type to JS Date and every output from JS Date to ISO string.
Is there a way to do it in the FE, that for every field that return a Date type will be automatically transformed to JS Date and will infer the type correctly?

**Comment by remorses** [comment] 2023-03-27 12:04
Graphql data is sent via JSON, where there is no Date type

I could add a custom serializer that transforms your date strings to Date objects but i don't really see much value in it, just add `new Date` in your code

**Comment by bennyk8y** [comment] 2023-03-27 15:35
Yea, problem is that if I add it to my code I need to do it in every date
field specifically for every query/mutation

**Comment by bennyk8y** [comment] 2023-04-11 11:36
I think there's much value in it.
For example in the server you have `Date` scalar that transform all dates. In the input it transforms it from ISO string to JS Date and in the output it transforms it from Date to ISO string.

While consuming this API, the Date type is `any` with genql.
If we could have transform it to Date it would make our life so much easier, because we could have work with dates everywhere.
We could have just `new Date(response.something.date)` but the Date scalar can be in any field and in any nesting level.
Only GQL layer is aware about the type of it.

**Comment by remorses** [comment] 2023-05-15 14:37
Closing this as duplicate of #57

**Closed by remorses** 2023-05-15 14:37 UTC
