### ISSUE TITLE
Adding unknown key to query doesn't show Typescript errors

### ISSUE THREAD

**Issue by davidfant** [remorses/genql#138] opened 2023-08-31 22:47 UTC
I've created a React hook that wraps genql. I get TS auto-complete as expected. However, I don't get any TS errors when adding keys that don't exist (e.g. `query: { somethingUnknown: true }` won't cause TS errors but will cause the query to fail (obviously). It would be good if generated types would include e.g. `[key: string]: never` to cause TS to throw errors when requesting keys that don't exist. E.g.

```ts
interface GenQLQuery {
  knownFields: ...
  [key: string]: never;
}
```

Here's my hook for reference:

```ts
export function useTypedQuery<Query extends query_rootGenqlSelection>(opts: {
  name: string;
  query: Query;
  pause?: boolean;
  requestPolicy?: RequestPolicy;
  context?: Partial<OperationContext>;
}) {
  const { query, variables } = generateQueryOp({ ...opts.query, __name: opts.name });
  return useQuery<QueryResult<Query>>({
    ...opts,
    query,
    variables,
  });
}
```

**Comment by remorses** [comment] 2023-09-01 08:02
This is a known issue caused by TypeScript generics, Genql uses the extends syntax which allows additional keys

**Comment by jasonkuhrt** [comment] 2023-12-14 19:20
Related https://github.com/remorses/genql/issues/158

This should be solvable, even more so now. Prisma Client used type helpers back when to make it happen, but IIUC its easier now thanks to TS changes mentioned in linked issue.

**Comment by aydangoon** [comment] 2024-02-27 16:58
Is there a fix for this? Running into the same issue

**Closed** 2024-11-19 08:00 UTC
